// Add your words here: { english: "word", level: "easy" | "middle" | "hard" | "reallyHard" }
const WORDS = {
  1: [
    { english: "trans/saction", level: "reallyHard" },
    { english: "trans/cend", level: "hard" },
    { english: "trans/mit", level: "middle" },
    { english: "trans/parent", level: "easy" },
    { english: "inter/fere", level: "middle" },
    { english: "inter/sect", level: "middle" },
    { english: "sub/merge", level: "hard" },
    { english: "ex/pel", level: "middle" },
    { english: "e/ject", level: "hard" },
    { english: "banish", level: "hard" },
    { english: "de/port", level: "hard" },
    { english: "eccentric", level: "hard" },
    { english: "explicit", level: "middle" },
    { english: "out/fit", level: "middle" },
    { english: "out/skirts", level: "middle" },
    { english: "out/weigh", level: "middle" },
    { english: "out/do", level: "hard" },
    { english: "out/number", level: "middle" },
    { english: "fore/bear", level: "hard" },
    { english: "fore/sight", level: "hard" },
    { english: "fore/head", level: "easy" },
    { english: "fore/man", level: "hard" },
    { english: "fore/show", level: "hard" },
    { english: "pre/cede", level: "middle" },
    { english: "pre/scribe", level: "middle" },
    { english: "diagnose", level: "middle" },
    { english: "pro/phet", level: "hard" },
    { english: "pro/phesy", level: "hard" },
    { english: "pro/long", level: "middle" },
    { english: "with/hold", level: "hard" },
    { english: "re/fine", level: "middle" },
    { english: "re/cede", level: "hard" },
    { english: "re/cession", level: "middle" },
    { english: "re/pel", level: "middle" },
    { english: "over/state", level: "hard" },
    { english: "over/shadow", level: "hard" },
    { english: "super/ficial", level: "hard" },
    { english: "super/fluous", level: "reallyHard" },
    { english: "surmount", level: "reallyHard" },
    { english: "under/mine", level: "hard" },
    { english: "under/privileged", level: "middle" },
    { english: "under/developed", level: "middle" },
    { english: "developing", level: "easy" },
    { english: "developed", level: "easy" },
    { english: "sub/conscious", level: "hard" },
    { english: "sub/ject", level: "middle" },
    { english: "sub/side", level: "hard" },
    { english: "sub/sides", level: "hard" },
    { english: "sub/sequent", level: "middle" },
    { english: "sub/ordinate", level: "hard" },
    { english: "de/preciate", level: "reallyHard" },
    { english: "de/nounce", level: "hard" },
    { english: "de/code", level: "middle" },
    { english: "en/code", level: "middle" },
  ],
  2: [
    { english: "in/consistent", level: "hard" },
    { english: "irresistibly", level: "reallyHard" },
    { english: "in/cessant", level: "reallyHard" },
    { english: "in/evitable", level: "middle" },
    { english: "dis/respectful", level: "middle" },
    { english: "respectable", level: "middle" },
    { english: "dis/arm", level: "middle" },
    { english: "un/bending", level: "middle" },
    { english: "stubborn", level: "middle" },
    { english: "ob/stinate", level: "hard" },
    { english: "subconscious", level: "hard" },
    { english: "counter/feit", level: "hard" },
    { english: "controversy", level: "hard" },
    { english: "contradict", level: "hard" },
    { english: "anti/agonism", level: "reallyHard" },
    { english: "anti/body", level: "middle" },
    { english: "anti/biotic", level: "middle" },
    { english: "anti/onym", level: "easy" },
    { english: "synonym", level: "easy" },
    { english: "anti/pathy", level: "hard" },
    { english: "ob/struct", level: "middle" },
  ],
  3: [
    { english: "madd/en", level: "hard" },
    { english: "morale", level: "middle" },
    { english: "de/moral/ize", level: "hard" },
    { english: "moral", level: "easy" },
    { english: "em/ancipate", level: "reallyHard" },
    { english: "equ/ate", level: "hard" },
    { english: "is subject to", level: "middle" },
    { english: "ample", level: "middle" },
    { english: "at best", level: "easy" },
    { english: "be about to", level: "easy" },
    { english: "it takes 사람/시간 to-v", level: "easy" },
    { english: "it takes 시간 for 사람 to-v", level: "middle" },
    { english: "cannot (help) but v", level: "hard" },
    { english: "cannot help v-ing", level: "middle" },
    { english: "be worth -ing", level: "middle" },
    { english: "there is no v-ing", level: "hard" },
    { english: "vice", level: "middle" },
    { english: "upon -ing", level: "middle" },
    { english: "in -ing", level: "middle" },
    { english: "deliberate", level: "hard" },
  ],
  4: [
    { english: "dog", level: "easy" },
    { english: "friend", level: "easy" },
    { english: "weather", level: "middle" },
    { english: "environment", level: "hard" },
    { english: "incomprehensible", level: "reallyHard" },
  ],
  5: [
    { english: "food", level: "easy" },
    { english: "happy", level: "easy" },
    { english: "history", level: "middle" },
    { english: "government", level: "hard" },
    { english: "uncharacteristically", level: "reallyHard" },
  ],
  6: [
    { english: "time", level: "easy" },
    { english: "city", level: "easy" },
    { english: "science", level: "middle" },
    { english: "technology", level: "hard" },
    { english: "misinterpretation", level: "reallyHard" },
  ],
  7: [
    { english: "day", level: "easy" },
    { english: "music", level: "easy" },
    { english: "culture", level: "middle" },
    { english: "responsibility", level: "hard" },
    { english: "counterintuitive", level: "reallyHard" },
  ],
  8: [
    { english: "night", level: "easy" },
    { english: "travel", level: "easy" },
    { english: "language", level: "middle" },
    { english: "communication", level: "hard" },
    { english: "anthropomorphism", level: "reallyHard" },
  ],
  9: [
    { english: "work", level: "easy" },
    { english: "money", level: "easy" },
    { english: "business", level: "middle" },
    { english: "entrepreneur", level: "hard" },
    { english: "idiosyncrasy", level: "reallyHard" },
  ],
  10: [
    { english: "love", level: "easy" },
    { english: "world", level: "easy" },
    { english: "society", level: "middle" },
    { english: "democracy", level: "hard" },
    { english: "quintessential", level: "reallyHard" },
  ],
  11: [
    { english: "life", level: "easy" },
    { english: "dream", level: "easy" },
    { english: "freedom", level: "middle" },
    { english: "philosophy", level: "hard" },
    { english: "serendipitous", level: "reallyHard" },
  ],
};
